### ISSUE TITLE
Redundant file

### ISSUE THREAD

**Issue by shivam-51** [shivam-51/postit#26]
postit/src/views/AppBlog.vue has been created 2 times.
Remove the unused one.

**Comment by shivam-51** [comment]
@BAAHUBALI7781  The commit message for the new PR should be "Removed extra AppBlog.vue Closes#26"

**Comment by shivam-51** [comment]
@BAAHUBALI7781 Is the issue clear?
Also remove itlab and main image

**Comment by BAAHUBALI7781** [comment]
> @BAAHUBALI7781 The commit message for the new PR should be "Removed extra AppBlog.vue Closes#26"

Removed AppBlog.vue from src/views!

**Comment by shivam-51** [comment]
where ?

**Comment by shivam-51** [comment]
Its difficult to track back with incomplete information.
linked at #33 and #32

**Comment by BAAHUBALI7781** [comment]
I sent a PR with the title "Added Team Page and remove additional AppBlog.vue file".
