### ISSUE TITLE
Add margin-bottom to blogging page

### ISSUE THREAD

**Issue by shivam-51** [shivam-51/postit#38]
On clicking on "Add Blog" from the Navbar the footer appears to close to the form. Try to shift it downwards.

Code Pointers :-
go to src/views/AddBlog.vue
add
```
.blogs {
    margin-bottom: 50px;
}
```
after `<style scoped>`
`

**Comment by cainwatson** [comment]
Hello @shivam-51! I can take this.

**Comment by shivam-51** [comment]
@cainwatson Sure please go ahead :)
