### ISSUE TITLE
add scoped to footer

### ISSUE THREAD

**Issue by shivam-51** [shivam-51/postit#40]
I cannot see why the style should not be scoped in src/components/Footer.vue.

Code Pointers:-
- go to src/components/Footer.vue
- change `<style>` to `<style scoped>`

**Comment by Nikblaze** [comment]
I would like to do it.

**Comment by shivam-51** [comment]
@Nikblaze Sure, Ill assign this to you

**Comment by shivam-51** [comment]
@Nikblaze Don't forget to check this out and suggest more issues.
