### ISSUE TITLE
Move the Login card to the center

### ISSUE THREAD

**Issue by shivam-51** [shivam-51/postit#44]
When clicking on the Login button. The login card seems to attached to the Navbar. Move it to the center of the page.

**Comment by shivam-51** [comment]
![Capture](https://user-images.githubusercontent.com/47945055/94815986-cec9f400-0418-11eb-8e6a-cce00cd30358.PNG)

**Comment by Avn007** [comment]
hey @shivam-51 , can I work on this issue ?

**Comment by shivam-51** [comment]
Sure, go ahead!

**Comment by vitormateusalmeida** [comment]
Solved #45
