### ISSUE TITLE
Highlight a Navbar tab only when that page is active

### ISSUE THREAD

**Issue by shivam-51** [shivam-51/postit#46]
The Navbar leads to mainly 3 major pages: "Blogs", "Threads" and "Meet the team".
All the 3 of these tabs remain in normal state throughout. Make a change such that the Blog tab gets `active` when we are on that page, Thread option gets `active` when we are on that page and so on..

**Comment by shivam-51** [comment]
![image](https://user-images.githubusercontent.com/47945055/94824873-181f4100-0423-11eb-816b-34f9d240bd10.png)

**Comment by muditjain33** [comment]
I am working on it.

**Comment by shivam-51** [comment]
@vitormateusalmeida Would you like to take this issue?

**Comment by muditjain33** [comment]
I have used this function in my site to do the same when put in script tag in navbar. But not familiar with vue bootstrap.
$(function(){
  var current_page_URL = location.href;
  $( "a" ).each(function() {
     if ($(this).attr("href") !== "#") {
       var target_URL = $(this).prop("href");
       if (target_URL == current_page_URL) {
          $('nav a').parents('li, ul').removeClass('active');
          $(this).parent('li').addClass('active');
          return false;
       }
     }
  });
});

**Comment by muditjain33** [comment]
`$(function(){
  var current_page_URL = location.href;
  $( "a" ).each(function() {
     if ($(this).attr("href") !== "#") {
       var target_URL = $(this).prop("href");
       if (target_URL == current_page_URL) {
          $('nav a').parents('li, ul').removeClass('active');
          $(this).parent('li').addClass('active');
          return false;
       }
     }
  });
});`

**Comment by VipinVIP** [comment]
I am interested to work on this issue . can you assign me

**Comment by shivam-51** [comment]
@VipinVIP Sure, go ahead
