### ISSUE TITLE
Make image responsive in Meet the Team

### ISSUE THREAD

**Issue by shivam-51** [shivam-51/postit#53]
On going to the "Meet the team" page from the Navbar, you get the profile of all developers. This page is not responsive.
Decrease the size of your browser or open this [link](https://postit-iiest.web.app/#/team) in your mobile and the image dislocates.
This should be fixed.

**Comment by RitikaShrestha-me** [comment]
Can you assign it to me?

**Comment by shivam-51** [comment]
@RitikaShrestha-me Sure, go ahead

**Comment by RitikaShrestha-me** [comment]
Have made it responsive and if there is any thoughts/requirements you may have in mind or any mistakes I have done then do let me know.

**Comment by shivam-51** [comment]
Looks good and works great. Thank You for your contribution @RitikaShrestha-me  :-)

**Comment by RitikaShrestha-me** [comment]
Thank you for giving the opportunity 🙂

> Looks good and works great. Thank You for your contribution @RitikaShrestha-me :-)
