### ISSUE TITLE
Make the home page mobile responsive

### ISSUE THREAD

**Issue by shivam-51** [shivam-51/postit#57]
The home page(first page when you open [this](https://postit-iiest.web.app/#/)) dislocates when opened in a smaller screen.
It should be fixed.

**Comment by shivam-51** [comment]
@RitikaShrestha-me Would you like to take this one? Pretty similar to your last issue it seems.

**Comment by iamsriranga** [comment]
@shivam-51, can i work on this

**Comment by shivam-51** [comment]
@saideepesh000 Sure, Go ahead

**Comment by RitikaShrestha-me** [comment]
Yes sure, but can I get some time to do it?

> @RitikaShrestha-me Would you like to take this one? Pretty similar to your last issue it seems.

**Comment by shivam-51** [comment]
sure, no hurry

**Comment by naomi-sharif** [comment]
Hi, is anyone working on this? I don't see anyone assigned? If not, I would like to assign myself ?

**Comment by iamsriranga** [comment]
> Hi, is anyone working on this? I don't see anyone assigned? If not, I would like to assign myself ?

I am working on it 🙂

**Comment by shivam-51** [comment]
Its been more than 7 days and there has been no update from @saideepesh000 . Unassigning him. Please comment back if you are still working on it @saideepesh000 .
Others are free to take on this issue.

**Comment by shivam-51** [comment]
@naomi-sharif would you like to?
